# Generated by Django 3.0.8 on 2020-07-22 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=50)),
                ('rollno', models.IntegerField()),
            ],
            options={
                'db_table': 'classstudent',
            },
        ),
    ]
